CREATE TABLE t_employee (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "c_name" VARCHAR(255) NOT NULL,
    "c_surname" VARCHAR(255) NOT NULL,
    "c_date_of_birth" DATE NOT NULL,
    "c_department" VARCHAR(255) NOT NULL,
    "c_salary" DECIMAL(10, 2) NOT NULL
);